In [76]:
import pandas as pd
import numpy as np

In [77]:
df=pd.read_csv("moviedataset/train.csv")
df.dtypes

id         int64
bin_0      int64
bin_1      int64
bin_2      int64
bin_3     object
bin_4     object
nom_0     object
nom_1     object
nom_2     object
nom_3     object
nom_4     object
nom_5     object
nom_6     object
nom_7     object
nom_8     object
nom_9     object
ord_0      int64
ord_1     object
ord_2     object
ord_3     object
ord_4     object
ord_5     object
day        int64
month      int64
target     int64
dtype: object

In [78]:
df

id  bin_0  bin_1  bin_2 bin_3 bin_4  nom_0      nom_1    nom_2  \
0            0      0      0      0     T     Y  Green   Triangle    Snake   
1            1      0      1      0     T     Y  Green  Trapezoid  Hamster   
2            2      0      0      0     F     Y   Blue  Trapezoid     Lion   
3            3      0      1      0     F     Y    Red  Trapezoid    Snake   
4            4      0      0      0     F     N    Red  Trapezoid     Lion   
...        ...    ...    ...    ...   ...   ...    ...        ...      ...   
299995  299995      0      0      0     T     N    Red  Trapezoid    Snake   
299996  299996      0      0      0     F     Y  Green  Trapezoid     Lion   
299997  299997      0      0      0     F     Y   Blue       Star  Axolotl   
299998  299998      0      1      0     F     Y  Green     Square  Axolotl   
299999  299999      0      0      0     F     Y   Blue  Trapezoid      Dog   

             nom_3  ...      nom_9 ord_0        ord_1        ord_2 ord_3  \
0          Finland  ...  2f4cb3d51     2  Grandmaster         Cold     h   
1           Russia  ...  f83c56c21     1  Grandmaster          Hot     a   
2           Russia  ...  ae6800dd0     1       Expert     Lava Hot     h   
3           Canada  ...  8270f0d71     1  Grandmaster  Boiling Hot     i   
4           Canada  ...  b164b72a7     1  Grandmaster     Freezing     a   
...            ...  ...        ...   ...          ...          ...   ...   
299995       India  ...  e027decef     1  Contributor     Freezing     k   
299996      Russia  ...  80f1411c8     2       Novice     Freezing     h   
299997      Russia  ...  314dcc15b     3       Novice  Boiling Hot     o   
299998  Costa Rica  ...  ab0ce192b     1       Master  Boiling Hot     h   
299999      Russia  ...  ad1af2b45     3  Contributor     Freezing     i   

       ord_4  ord_5 day month target  
0          D     kr   2     2      0  
1          A     bF   7     8      0  
2          R     Jc   7     2      0  
3          D     kW   2     1      1  
4          R     qP   7     8      0  
...      ...    ...  ..   ...    ...  
299995     K     dh   3     8      0  
299996     W     MO   3     2      0  
299997     A     Bn   7     9      1  
299998     W     uJ   3     8      1  
299999     R     tP   1     3      0  

[300000 rows x 25 columns]

In [79]:
X_train=df.iloc[:,:-1].values
y_train=df.iloc[:,1].values

In [91]:
l={4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21}

In [92]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [93]:
for i in range(0,24):
    if (i in l):
        label_X_train=LabelEncoder()
        X_train[:,i]=label_X_train.fit_transform(X_train[:,i])
transformer=ColumnTransformer([('one_hot_encoder',OneHotEncoder(categories='auto'),[1])],remainder='passthrough')
X_train=np.array(transformer.fit_transform(X_train),dtype=float)

In [94]:
X_train

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.36000e+02,
        2.00000e+00, 2.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, ..., 9.30000e+01,
        7.00000e+00, 8.00000e+00],
       [1.00000e+00, 0.00000e+00, 2.00000e+00, ..., 3.10000e+01,
        7.00000e+00, 2.00000e+00],
       ...,
       [1.00000e+00, 0.00000e+00, 2.99997e+05, ..., 7.00000e+00,
        7.00000e+00, 9.00000e+00],
       [1.00000e+00, 0.00000e+00, 2.99998e+05, ..., 1.74000e+02,
        3.00000e+00, 8.00000e+00],
       [1.00000e+00, 0.00000e+00, 2.99999e+05, ..., 1.72000e+02,
        1.00000e+00, 3.00000e+00]])

In [95]:
test=pd.read_csv("moviedataset/test.csv")
test.dtypes

id        int64
bin_0     int64
bin_1     int64
bin_2     int64
bin_3    object
bin_4    object
nom_0    object
nom_1    object
nom_2    object
nom_3    object
nom_4    object
nom_5    object
nom_6    object
nom_7    object
nom_8    object
nom_9    object
ord_0     int64
ord_1    object
ord_2    object
ord_3    object
ord_4    object
ord_5    object
day       int64
month     int64
dtype: object

In [96]:
li={4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21}

In [97]:
X_test=test.iloc[:,:].values

In [98]:
for i in range(0,24):
    if(i in li):
        label_X_test=LabelEncoder()
        X_test[:,i]=label_X_test.fit_transform(X_test[:,i])
transformer1=ColumnTransformer([('one_hot_encoder',OneHotEncoder(categories='auto'),[1])],remainder='passthrough')
X_test=np.array(transformer1.fit_transform(X_test),dtype=float)

In [99]:
X_test

array([[1.00000e+00, 0.00000e+00, 3.00000e+05, ..., 9.50000e+01,
        5.00000e+00, 1.10000e+01],
       [1.00000e+00, 0.00000e+00, 3.00001e+05, ..., 6.10000e+01,
        7.00000e+00, 5.00000e+00],
       [0.00000e+00, 1.00000e+00, 3.00002e+05, ..., 1.72000e+02,
        1.00000e+00, 1.20000e+01],
       ...,
       [1.00000e+00, 0.00000e+00, 4.99997e+05, ..., 6.60000e+01,
        3.00000e+00, 1.00000e+00],
       [0.00000e+00, 1.00000e+00, 4.99998e+05, ..., 8.20000e+01,
        2.00000e+00, 1.00000e+00],
       [1.00000e+00, 0.00000e+00, 4.99999e+05, ..., 1.14000e+02,
        2.00000e+00, 2.00000e+00]])

In [100]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
drugTree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [102]:
y_test=drugTree.predict(X_test)

In [103]:
y_test

array([0, 0, 1, ..., 0, 1, 0])

In [104]:
results = np.argmax(y_test,axis = 0)

data_out = pd.DataFrame({'id': range(1,len(X_test)+1), 'target': results})
data_out.to_csv('subm.csv', index = None)